using STICKET.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;

namespace STICKET.Models
{
    public class InicioDb : CreateDatabaseIfNotExists<STIContext>
    {
        protected override void Seed(STIContext context)
        {
            context.Regiones.AddOrUpdate(
                r => r.Id,
                new Region { Id = 1, Nombre = " I Tarapacá" },
                new Region { Id = 2, Nombre = " II Antofagasta" },
                new Region { Id = 3, Nombre = "III Atacama" },
                new Region { Id = 4, Nombre = "IV Coquimbo" },
                new Region { Id = 5, Nombre = "V Valparaíso" },
                new Region { Id = 6, Nombre = " VI Región del Libertador Gral. Bernardo O’Higgins" },
                new Region { Id = 7, Nombre = "VII Región del Maule" },
                new Region { Id = 8, Nombre = "VIII Región del Biobío" },
                new Region { Id = 9, Nombre = "IX Región de la Araucanía" },
                new Region { Id = 10, Nombre = "X Región de Los Lagos" },
                new Region { Id = 11, Nombre = "XI Región Aisén del Gral. Carlos Ibáñez del Campo" },
                new Region { Id = 12, Nombre = "XII Región de Magallanes y de la Antártica Chilena" },
                new Region { Id = 13, Nombre = "XIII Región Metropolitana de Santiago" },
                new Region { Id = 14, Nombre = "XIV Región de Los Ríos" },
                new Region { Id = 15, Nombre = "XV Arica y Parinacota" }
                );
            context.Provincias.AddOrUpdate(
                p => p.Id,
                new Provincia { Id = 1, Nombre = "Arica", RegionId = 15 },
                new Provincia { Id = 2, Nombre = "Parinacota", RegionId = 15 },
                new Provincia { Id = 3, Nombre = "Iquique", RegionId = 1 },
                new Provincia { Id = 4, Nombre = "Tamarugal", RegionId = 1 },
                new Provincia { Id = 5, Nombre = "Antofagasta", RegionId = 2 },
                new Provincia { Id = 6, Nombre = "El Loa", RegionId = 2 },
                new Provincia { Id = 7, Nombre = "Tocopilla", RegionId = 2 },
                new Provincia { Id = 8, Nombre = "Copiapó", RegionId = 3 },
                new Provincia { Id = 9, Nombre = "Chañaral", RegionId = 3 },
                new Provincia { Id = 10, Nombre = "Huasco", RegionId = 3 },
                new Provincia { Id = 11, Nombre = "Elqui", RegionId = 4 },
                new Provincia { Id = 12, Nombre = "Choapa", RegionId = 4 },
                new Provincia { Id = 13, Nombre = "Limarí", RegionId = 4 },
                new Provincia { Id = 14, Nombre = "Valparaíso", RegionId = 5 },
                new Provincia { Id = 15, Nombre = "Isla de Pascua", RegionId = 5 },
                new Provincia { Id = 16, Nombre = "Los Andes", RegionId = 5 },
                new Provincia { Id = 17, Nombre = "Petorca", RegionId = 5 },
                new Provincia { Id = 18, Nombre = "Quillota", RegionId = 5 },
                new Provincia { Id = 19, Nombre = "San Antonio", RegionId = 5 },
                new Provincia { Id = 20, Nombre = "San Felipe de Aconcagua", RegionId = 5 },
                new Provincia { Id = 21, Nombre = "Marga Marga", RegionId = 5 },
                new Provincia { Id = 22, Nombre = "Cachapoal", RegionId = 6 },
                new Provincia { Id = 23, Nombre = "Cardenal Caro", RegionId = 6 },
                new Provincia { Id = 24, Nombre = "Colchagua", RegionId = 6 },
                new Provincia { Id = 25, Nombre = "Talca", RegionId = 7 },
                new Provincia { Id = 26, Nombre = "Cauquenes", RegionId = 7 },
                new Provincia { Id = 27, Nombre = "Curicó", RegionId = 7 },
                new Provincia { Id = 28, Nombre = "Linares", RegionId = 7 },
                new Provincia { Id = 29, Nombre = "Concepción", RegionId = 8 },
                new Provincia { Id = 30, Nombre = "Arauco", RegionId = 8 },
                new Provincia { Id = 31, Nombre = "Biobío", RegionId = 8 },
                new Provincia { Id = 32, Nombre = "Ñuble", RegionId = 8 },
                new Provincia { Id = 33, Nombre = "Cautín", RegionId = 9 },
                new Provincia { Id = 34, Nombre = "Malleco", RegionId = 9 },
                new Provincia { Id = 35, Nombre = "Valdivia", RegionId = 14 },
                new Provincia { Id = 36, Nombre = "Ranco", RegionId = 14 },
                new Provincia { Id = 37, Nombre = "Llanquihue", RegionId = 10 },
                new Provincia { Id = 38, Nombre = "Chiloé", RegionId = 10 },
                new Provincia { Id = 39, Nombre = "Osorno", RegionId = 10 },
                new Provincia { Id = 40, Nombre = "Palena", RegionId = 10 },
                new Provincia { Id = 41, Nombre = "Coihaique", RegionId = 11 },
                new Provincia { Id = 42, Nombre = "Aisén", RegionId = 11 },
                new Provincia { Id = 43, Nombre = "Capitán Prat", RegionId = 11 },
                new Provincia { Id = 44, Nombre = "General Carrera", RegionId = 11 },
                new Provincia { Id = 45, Nombre = "Magallanes", RegionId = 12 },
                new Provincia { Id = 46, Nombre = "Antártica Chilena", RegionId = 12 },
                new Provincia { Id = 47, Nombre = "Tierra del Fuego", RegionId = 12 },
                new Provincia { Id = 48, Nombre = "Última Esperanza", RegionId = 12 },
                new Provincia { Id = 49, Nombre = "Santiago", RegionId = 13 },
                new Provincia { Id = 50, Nombre = "Cordillera", RegionId = 13 },
                new Provincia { Id = 51, Nombre = "Chacabuco", RegionId = 13 },
                new Provincia { Id = 52, Nombre = "Maipo", RegionId = 13 },
                new Provincia { Id = 53, Nombre = "Melipilla", RegionId = 13 },
                new Provincia { Id = 54, Nombre = "Talagante", RegionId = 13 }
                );
            context.Comunas.AddOrUpdate(
                c => c.Id,
                new Comuna { Id = 1, Nombre = "Iquique", ProvinciaId = 3 },
                new Comuna { Id = 2, Nombre = "Alto Hospicio", ProvinciaId = 3 },
                new Comuna { Id = 3, Nombre = "Pozo Almonte", ProvinciaId = 4 },
                new Comuna { Id = 4, Nombre = "Camiña", ProvinciaId = 4 },
                new Comuna { Id = 5, Nombre = "Colchane", ProvinciaId = 4 },
                new Comuna { Id = 6, Nombre = "Huara", ProvinciaId = 4 },
                new Comuna { Id = 7, Nombre = "Pica", ProvinciaId = 4 },
                new Comuna { Id = 8, Nombre = "Antofagasta", ProvinciaId = 5 },
                new Comuna { Id = 9, Nombre = "Mejillones", ProvinciaId = 5 },
                new Comuna { Id = 10, Nombre = "Sierra Gorda", ProvinciaId = 5 },
                new Comuna { Id = 11, Nombre = "Taltal", ProvinciaId = 5 },
                new Comuna { Id = 12, Nombre = "Calama", ProvinciaId = 6 },
                new Comuna { Id = 13, Nombre = "Ollagüe", ProvinciaId = 6 },
                new Comuna { Id = 14, Nombre = "San Pedro de Atacama", ProvinciaId = 6 },
                new Comuna { Id = 15, Nombre = "Tocopilla", ProvinciaId = 7 },
                new Comuna { Id = 16, Nombre = "María Elena", ProvinciaId = 7 },
                new Comuna { Id = 17, Nombre = "Copiapó", ProvinciaId = 8 },
                new Comuna { Id = 18, Nombre = "Caldera", ProvinciaId = 8 },
                new Comuna { Id = 19, Nombre = "Tierra Amarilla", ProvinciaId = 8 },
                new Comuna { Id = 20, Nombre = "Chañaral", ProvinciaId = 9 },
                new Comuna { Id = 21, Nombre = "Diego de Almagro", ProvinciaId = 9 },
                new Comuna { Id = 22, Nombre = "Vallenar", ProvinciaId = 10 },
                new Comuna { Id = 23, Nombre = "Alto del Carmen", ProvinciaId = 10 },
                new Comuna { Id = 24, Nombre = "Freirina", ProvinciaId = 10 },
                new Comuna { Id = 25, Nombre = "Huasco", ProvinciaId = 10 },
                new Comuna { Id = 26, Nombre = "La Serena", ProvinciaId = 11 },
                new Comuna { Id = 27, Nombre = "Coquimbo", ProvinciaId = 11 },
                new Comuna { Id = 28, Nombre = "Andacollo", ProvinciaId = 11 },
                new Comuna { Id = 29, Nombre = "La Higuera", ProvinciaId = 11 },
                new Comuna { Id = 30, Nombre = "Paihuano", ProvinciaId = 11 },
                new Comuna { Id = 31, Nombre = "Vicuña", ProvinciaId = 11 },
                new Comuna { Id = 32, Nombre = "Illapel", ProvinciaId = 12 },
                new Comuna { Id = 33, Nombre = "Canela", ProvinciaId = 12 },
                new Comuna { Id = 34, Nombre = "Los Vilos", ProvinciaId = 12 },
                new Comuna { Id = 35, Nombre = "Salamanca", ProvinciaId = 12 },
                new Comuna { Id = 36, Nombre = "Ovalle", ProvinciaId = 13 },
                new Comuna { Id = 37, Nombre = "Combarbalá", ProvinciaId = 13 },
                new Comuna { Id = 38, Nombre = "Monte Patria", ProvinciaId = 13 },
                new Comuna { Id = 39, Nombre = "Punitaqui", ProvinciaId = 13 },
                new Comuna { Id = 40, Nombre = "Río Hurtado", ProvinciaId = 13 },
                new Comuna { Id = 41, Nombre = "Valparaíso", ProvinciaId = 14 },
                new Comuna { Id = 42, Nombre = "Casablanca", ProvinciaId = 14 },
                new Comuna { Id = 43, Nombre = "Concón", ProvinciaId = 14 },
                new Comuna { Id = 44, Nombre = "Juan Fernández", ProvinciaId = 14 },
                new Comuna { Id = 45, Nombre = "Puchuncaví", ProvinciaId = 14 },
                new Comuna { Id = 46, Nombre = "Quintero", ProvinciaId = 14 },
                new Comuna { Id = 47, Nombre = "Viña del Mar", ProvinciaId = 14 },
                new Comuna { Id = 48, Nombre = "Isla de Pascua", ProvinciaId = 15 },
                new Comuna { Id = 49, Nombre = "Los Andes", ProvinciaId = 16 },
                new Comuna { Id = 50, Nombre = "Calle Larga", ProvinciaId = 16 },
                new Comuna { Id = 51, Nombre = "Rinconada", ProvinciaId = 16 },
                new Comuna { Id = 52, Nombre = "San Esteban", ProvinciaId = 16 },
                new Comuna { Id = 53, Nombre = "La Ligua", ProvinciaId = 17 },
                new Comuna { Id = 54, Nombre = "Cabildo", ProvinciaId = 17 },
                new Comuna { Id = 55, Nombre = "Papudo", ProvinciaId = 17 },
                new Comuna { Id = 56, Nombre = "Petorca", ProvinciaId = 17 },
                new Comuna { Id = 57, Nombre = "Zapallar", ProvinciaId = 17 },
                new Comuna { Id = 58, Nombre = "Quillota", ProvinciaId = 18 },
                new Comuna { Id = 59, Nombre = "La Calera", ProvinciaId = 18 },
                new Comuna { Id = 60, Nombre = "Hijuelas", ProvinciaId = 18 },
                new Comuna { Id = 61, Nombre = "La Cruz", ProvinciaId = 18 },
                new Comuna { Id = 62, Nombre = "Nogales", ProvinciaId = 18 },
                new Comuna { Id = 63, Nombre = "San Antonio", ProvinciaId = 19 },
                new Comuna { Id = 64, Nombre = "Algarrobo", ProvinciaId = 19 },
                new Comuna { Id = 65, Nombre = "Cartagena", ProvinciaId = 19 },
                new Comuna { Id = 66, Nombre = "El Quisco", ProvinciaId = 19 },
                new Comuna { Id = 67, Nombre = "El Tabo", ProvinciaId = 19 },
                new Comuna { Id = 68, Nombre = "Santo Domingo", ProvinciaId = 19 },
                new Comuna { Id = 69, Nombre = "San Felipe", ProvinciaId = 20 },
                new Comuna { Id = 70, Nombre = "Catemu", ProvinciaId = 20 },
                new Comuna { Id = 71, Nombre = "Llay Llay", ProvinciaId = 20 },
                new Comuna { Id = 72, Nombre = "Panquehue", ProvinciaId = 20 },
                new Comuna { Id = 73, Nombre = "Putaendo", ProvinciaId = 20 },
                new Comuna { Id = 74, Nombre = "Santa María", ProvinciaId = 20 },
                new Comuna { Id = 75, Nombre = "Quilpué", ProvinciaId = 21 },
                new Comuna { Id = 76, Nombre = "Limache", ProvinciaId = 21 },
                new Comuna { Id = 77, Nombre = "Olmué", ProvinciaId = 21 },
                new Comuna { Id = 78, Nombre = "Villa Alemana", ProvinciaId = 21 },
                new Comuna { Id = 79, Nombre = "Rancagua", ProvinciaId = 22 },
                new Comuna { Id = 80, Nombre = "Codegua", ProvinciaId = 22 },
                new Comuna { Id = 81, Nombre = "Coinco", ProvinciaId = 22 },
                new Comuna { Id = 82, Nombre = "Coltauco", ProvinciaId = 22 },
                new Comuna { Id = 83, Nombre = "Doñihue", ProvinciaId = 22 },
                new Comuna { Id = 84, Nombre = "Graneros", ProvinciaId = 22 },
                new Comuna { Id = 85, Nombre = "Las Cabras", ProvinciaId = 22 },
                new Comuna { Id = 86, Nombre = "Machalí", ProvinciaId = 22 },
                new Comuna { Id = 87, Nombre = "Malloa", ProvinciaId = 22 },
                new Comuna { Id = 88, Nombre = "Mostazal", ProvinciaId = 22 },
                new Comuna { Id = 89, Nombre = "Olivar", ProvinciaId = 22 },
                new Comuna { Id = 90, Nombre = "Peumo", ProvinciaId = 22 },
                new Comuna { Id = 91, Nombre = "Pichidegua", ProvinciaId = 22 },
                new Comuna { Id = 92, Nombre = "Quinta de Tilcoco", ProvinciaId = 22 },
                new Comuna { Id = 93, Nombre = "Rengo", ProvinciaId = 22 },
                new Comuna { Id = 94, Nombre = "Requínoa", ProvinciaId = 22 },
                new Comuna { Id = 95, Nombre = "San Vicente", ProvinciaId = 22 },
                new Comuna { Id = 96, Nombre = "Pichilemu", ProvinciaId = 23 },
                new Comuna { Id = 97, Nombre = "La Estrella", ProvinciaId = 23 },
                new Comuna { Id = 98, Nombre = "Litueche", ProvinciaId = 23 },
                new Comuna { Id = 99, Nombre = "Marchihue", ProvinciaId = 23 },
                new Comuna { Id = 100, Nombre = "Navidad", ProvinciaId = 23 },
                new Comuna { Id = 101, Nombre = "Paredones", ProvinciaId = 23 },
                new Comuna { Id = 102, Nombre = "San Fernando", ProvinciaId = 24 },
                new Comuna { Id = 103, Nombre = "Chépica", ProvinciaId = 24 },
                new Comuna { Id = 104, Nombre = "Chimbarongo", ProvinciaId = 24 },
                new Comuna { Id = 105, Nombre = "Lolol", ProvinciaId = 24 },
                new Comuna { Id = 106, Nombre = "Nancagua", ProvinciaId = 24 },
                new Comuna { Id = 107, Nombre = "Palmilla", ProvinciaId = 24 },
                new Comuna { Id = 108, Nombre = "Peralillo", ProvinciaId = 24 },
                new Comuna { Id = 109, Nombre = "Placilla", ProvinciaId = 24 },
                new Comuna { Id = 110, Nombre = "Pumanque", ProvinciaId = 24 },
                new Comuna { Id = 111, Nombre = "Santa Cruz", ProvinciaId = 24 },
                new Comuna { Id = 112, Nombre = "Talca", ProvinciaId = 25 },
                new Comuna { Id = 113, Nombre = "Constitución", ProvinciaId = 25 },
                new Comuna { Id = 114, Nombre = "Curepto", ProvinciaId = 25 },
                new Comuna { Id = 115, Nombre = "Empedrado", ProvinciaId = 25 },
                new Comuna { Id = 116, Nombre = "Maule", ProvinciaId = 25 },
                new Comuna { Id = 117, Nombre = "Pelarco", ProvinciaId = 25 },
                new Comuna { Id = 118, Nombre = "Pencahue", ProvinciaId = 25 },
                new Comuna { Id = 119, Nombre = "Río Claro", ProvinciaId = 25 },
                new Comuna { Id = 120, Nombre = "San Clemente", ProvinciaId = 25 },
                new Comuna { Id = 121, Nombre = "San Rafael", ProvinciaId = 25 },
                new Comuna { Id = 122, Nombre = "Cauquenes", ProvinciaId = 26 },
                new Comuna { Id = 123, Nombre = "Chanco", ProvinciaId = 26 },
                new Comuna { Id = 124, Nombre = "Pelluhue", ProvinciaId = 26 },
                new Comuna { Id = 125, Nombre = "Curicó", ProvinciaId = 27 },
                new Comuna { Id = 126, Nombre = "Hualañé", ProvinciaId = 27 },
                new Comuna { Id = 127, Nombre = "Licantén", ProvinciaId = 27 },
                new Comuna { Id = 128, Nombre = "Molina", ProvinciaId = 27 },
                new Comuna { Id = 129, Nombre = "Rauco", ProvinciaId = 27 },
                new Comuna { Id = 130, Nombre = "Romeral", ProvinciaId = 27 },
                new Comuna { Id = 131, Nombre = "Sagrada Familia", ProvinciaId = 27 },
                new Comuna { Id = 132, Nombre = "Teno", ProvinciaId = 27 },
                new Comuna { Id = 133, Nombre = "Vichuquén", ProvinciaId = 27 },
                new Comuna { Id = 134, Nombre = "Linares", ProvinciaId = 28 },
                new Comuna { Id = 135, Nombre = "Colbún", ProvinciaId = 28 },
                new Comuna { Id = 136, Nombre = "Longaví", ProvinciaId = 28 },
                new Comuna { Id = 137, Nombre = "Parral", ProvinciaId = 28 },
                new Comuna { Id = 138, Nombre = "Retiro", ProvinciaId = 28 },
                new Comuna { Id = 139, Nombre = "San Javier", ProvinciaId = 28 },
                new Comuna { Id = 140, Nombre = "Villa Alegre", ProvinciaId = 28 },
                new Comuna { Id = 141, Nombre = "Yerbas Buenas", ProvinciaId = 28 },
                new Comuna { Id = 142, Nombre = "Concepción", ProvinciaId = 29 },
                new Comuna { Id = 143, Nombre = "Coronel", ProvinciaId = 29 },
                new Comuna { Id = 144, Nombre = "Chiguayante", ProvinciaId = 29 },
                new Comuna { Id = 145, Nombre = "Florida", ProvinciaId = 29 },
                new Comuna { Id = 146, Nombre = "Hualqui", ProvinciaId = 29 },
                new Comuna { Id = 147, Nombre = "Lota", ProvinciaId = 29 },
                new Comuna { Id = 148, Nombre = "Penco", ProvinciaId = 29 },
                new Comuna { Id = 149, Nombre = "San Pedro de la Paz", ProvinciaId = 29 },
                new Comuna { Id = 150, Nombre = "Santa Juana", ProvinciaId = 29 },
                new Comuna { Id = 151, Nombre = "Talcahuano", ProvinciaId = 29 },
                new Comuna { Id = 152, Nombre = "Tomé", ProvinciaId = 29 },
                new Comuna { Id = 153, Nombre = "Hualpén", ProvinciaId = 29 },
                new Comuna { Id = 154, Nombre = "Lebu", ProvinciaId = 30 },
                new Comuna { Id = 155, Nombre = "Arauco", ProvinciaId = 30 },
                new Comuna { Id = 156, Nombre = "Cañete", ProvinciaId = 30 },
                new Comuna { Id = 157, Nombre = "Contulmo", ProvinciaId = 30 },
                new Comuna { Id = 158, Nombre = "Curanilahue", ProvinciaId = 30 },
                new Comuna { Id = 159, Nombre = "Los Álamos", ProvinciaId = 30 },
                new Comuna { Id = 160, Nombre = "Tirúa", ProvinciaId = 30 },
                new Comuna { Id = 161, Nombre = "Los Ángeles", ProvinciaId = 31 },
                new Comuna { Id = 162, Nombre = "Antuco", ProvinciaId = 31 },
                new Comuna { Id = 163, Nombre = "Cabrero", ProvinciaId = 31 },
                new Comuna { Id = 164, Nombre = "Laja", ProvinciaId = 31 },
                new Comuna { Id = 165, Nombre = "Mulchén", ProvinciaId = 31 },
                new Comuna { Id = 166, Nombre = "Nacimiento", ProvinciaId = 31 },
                new Comuna { Id = 167, Nombre = "Negrete", ProvinciaId = 31 },
                new Comuna { Id = 168, Nombre = "Quilaco", ProvinciaId = 31 },
                new Comuna { Id = 169, Nombre = "Quilleco", ProvinciaId = 31 },
                new Comuna { Id = 170, Nombre = "San Rosendo", ProvinciaId = 31 },
                new Comuna { Id = 171, Nombre = "Santa Bárbara", ProvinciaId = 31 },
                new Comuna { Id = 172, Nombre = "Tucapel", ProvinciaId = 31 },
                new Comuna { Id = 173, Nombre = "Yumbel", ProvinciaId = 31 },
                new Comuna { Id = 174, Nombre = "Alto Biobío", ProvinciaId = 31 },
                new Comuna { Id = 175, Nombre = "Chillán", ProvinciaId = 32 },
                new Comuna { Id = 176, Nombre = "Bulnes", ProvinciaId = 32 },
                new Comuna { Id = 177, Nombre = "Cobquecura", ProvinciaId = 32 },
                new Comuna { Id = 178, Nombre = "Coelemu", ProvinciaId = 32 },
                new Comuna { Id = 179, Nombre = "Coihueco", ProvinciaId = 32 },
                new Comuna { Id = 180, Nombre = "Chillán Viejo", ProvinciaId = 32 },
                new Comuna { Id = 181, Nombre = "El Carmen", ProvinciaId = 32 },
                new Comuna { Id = 182, Nombre = "Ninhue", ProvinciaId = 32 },
                new Comuna { Id = 183, Nombre = "Ñiquén", ProvinciaId = 32 },
                new Comuna { Id = 184, Nombre = "Pemuco", ProvinciaId = 32 },
                new Comuna { Id = 185, Nombre = "Pinto", ProvinciaId = 32 },
                new Comuna { Id = 186, Nombre = "Portezuelo", ProvinciaId = 32 },
                new Comuna { Id = 187, Nombre = "Quillón", ProvinciaId = 32 },
                new Comuna { Id = 188, Nombre = "Quirihue", ProvinciaId = 32 },
                new Comuna { Id = 189, Nombre = "Ránquil", ProvinciaId = 32 },
                new Comuna { Id = 190, Nombre = "San Carlos", ProvinciaId = 32 },
                new Comuna { Id = 191, Nombre = "San Fabián", ProvinciaId = 32 },
                new Comuna { Id = 192, Nombre = "San Ignacio", ProvinciaId = 32 },
                new Comuna { Id = 193, Nombre = "San Nicolás", ProvinciaId = 32 },
                new Comuna { Id = 194, Nombre = "Treguaco", ProvinciaId = 32 },
                new Comuna { Id = 195, Nombre = "Yungay", ProvinciaId = 32 },
                new Comuna { Id = 196, Nombre = "Temuco", ProvinciaId = 33 },
                new Comuna { Id = 197, Nombre = "Carahue", ProvinciaId = 33 },
                new Comuna { Id = 198, Nombre = "Cunco", ProvinciaId = 33 },
                new Comuna { Id = 199, Nombre = "Curarrehue", ProvinciaId = 33 },
                new Comuna { Id = 200, Nombre = "Freire", ProvinciaId = 33 },
                new Comuna { Id = 201, Nombre = "Galvarino", ProvinciaId = 33 },
                new Comuna { Id = 202, Nombre = "Gorbea", ProvinciaId = 33 },
                new Comuna { Id = 203, Nombre = "Lautaro", ProvinciaId = 33 },
                new Comuna { Id = 204, Nombre = "Loncoche", ProvinciaId = 33 },
                new Comuna { Id = 205, Nombre = "Melipeuco", ProvinciaId = 33 },
                new Comuna { Id = 206, Nombre = "Nueva Imperial", ProvinciaId = 33 },
                new Comuna { Id = 207, Nombre = "Padre las Casas", ProvinciaId = 33 },
                new Comuna { Id = 208, Nombre = "Perquenco", ProvinciaId = 33 },
                new Comuna { Id = 209, Nombre = "Pitrufquén", ProvinciaId = 33 },
                new Comuna { Id = 210, Nombre = "Pucón", ProvinciaId = 33 },
                new Comuna { Id = 211, Nombre = "Saavedra", ProvinciaId = 33 },
                new Comuna { Id = 212, Nombre = "Teodoro Schmidt", ProvinciaId = 33 },
                new Comuna { Id = 213, Nombre = "Toltén", ProvinciaId = 33 },
                new Comuna { Id = 214, Nombre = "Vilcún", ProvinciaId = 33 },
                new Comuna { Id = 215, Nombre = "Villarrica", ProvinciaId = 33 },
                new Comuna { Id = 216, Nombre = "Cholchol", ProvinciaId = 33 },
                new Comuna { Id = 217, Nombre = "Angol", ProvinciaId = 34 },
                new Comuna { Id = 218, Nombre = "Collipulli", ProvinciaId = 34 },
                new Comuna { Id = 219, Nombre = "Curacautín", ProvinciaId = 34 },
                new Comuna { Id = 220, Nombre = "Ercilla", ProvinciaId = 34 },
                new Comuna { Id = 221, Nombre = "Lonquimay", ProvinciaId = 34 },
                new Comuna { Id = 222, Nombre = "Los Sauces", ProvinciaId = 34 },
                new Comuna { Id = 223, Nombre = "Lumaco", ProvinciaId = 34 },
                new Comuna { Id = 224, Nombre = "Purén", ProvinciaId = 34 },
                new Comuna { Id = 225, Nombre = "Renaico", ProvinciaId = 34 },
                new Comuna { Id = 226, Nombre = "Traiguén", ProvinciaId = 34 },
                new Comuna { Id = 227, Nombre = "Victoria", ProvinciaId = 34 },
                new Comuna { Id = 228, Nombre = "Puerto Montt", ProvinciaId = 37 },
                new Comuna { Id = 229, Nombre = "Calbuco", ProvinciaId = 37 },
                new Comuna { Id = 230, Nombre = "Cochamó", ProvinciaId = 37 },
                new Comuna { Id = 231, Nombre = "Fresia", ProvinciaId = 37 },
                new Comuna { Id = 232, Nombre = "Frutillar", ProvinciaId = 37 },
                new Comuna { Id = 233, Nombre = "Los Muermos", ProvinciaId = 37 },
                new Comuna { Id = 234, Nombre = "Llanquihue", ProvinciaId = 37 },
                new Comuna { Id = 235, Nombre = "Maullín", ProvinciaId = 37 },
                new Comuna { Id = 236, Nombre = "Puerto Varas", ProvinciaId = 37 },
                new Comuna { Id = 237, Nombre = "Castro", ProvinciaId = 38 },
                new Comuna { Id = 238, Nombre = "Ancud", ProvinciaId = 38 },
                new Comuna { Id = 239, Nombre = "Chonchi", ProvinciaId = 38 },
                new Comuna { Id = 240, Nombre = "Curaco de Vélez", ProvinciaId = 38 },
                new Comuna { Id = 241, Nombre = "Dalcahue", ProvinciaId = 38 },
                new Comuna { Id = 242, Nombre = "Puqueldón", ProvinciaId = 38 },
                new Comuna { Id = 243, Nombre = "Queilén", ProvinciaId = 38 },
                new Comuna { Id = 244, Nombre = "Quellón", ProvinciaId = 38 },
                new Comuna { Id = 245, Nombre = "Quemchi", ProvinciaId = 38 },
                new Comuna { Id = 246, Nombre = "Quinchao", ProvinciaId = 38 },
                new Comuna { Id = 247, Nombre = "Osorno", ProvinciaId = 39 },
                new Comuna { Id = 248, Nombre = "Puerto Octay", ProvinciaId = 39 },
                new Comuna { Id = 249, Nombre = "Purranque", ProvinciaId = 39 },
                new Comuna { Id = 250, Nombre = "Puyehue", ProvinciaId = 39 },
                new Comuna { Id = 251, Nombre = "Río Negro", ProvinciaId = 39 },
                new Comuna { Id = 252, Nombre = "San Juan de la Costa", ProvinciaId = 39 },
                new Comuna { Id = 253, Nombre = "San Pablo", ProvinciaId = 39 },
                new Comuna { Id = 254, Nombre = "Chaitén", ProvinciaId = 40 },
                new Comuna { Id = 255, Nombre = "Futaleufú", ProvinciaId = 40 },
                new Comuna { Id = 256, Nombre = "Hualaihué", ProvinciaId = 40 },
                new Comuna { Id = 257, Nombre = "Palena", ProvinciaId = 40 },
                new Comuna { Id = 258, Nombre = "Coyhaique", ProvinciaId = 41 },
                new Comuna { Id = 259, Nombre = "Lago Verde", ProvinciaId = 41 },
                new Comuna { Id = 260, Nombre = "Aysén", ProvinciaId = 42 },
                new Comuna { Id = 261, Nombre = "Cisnes", ProvinciaId = 42 },
                new Comuna { Id = 262, Nombre = "Guaitecas", ProvinciaId = 42 },
                new Comuna { Id = 263, Nombre = "Cochrane", ProvinciaId = 43 },
                new Comuna { Id = 264, Nombre = "O’Higgins", ProvinciaId = 43 },
                new Comuna { Id = 265, Nombre = "Tortel", ProvinciaId = 43 },
                new Comuna { Id = 266, Nombre = "Chile Chico", ProvinciaId = 44 },
                new Comuna { Id = 267, Nombre = "Río Ibáñez", ProvinciaId = 44 },
                new Comuna { Id = 268, Nombre = "Punta Arenas", ProvinciaId = 45 },
                new Comuna { Id = 269, Nombre = "Laguna Blanca", ProvinciaId = 45 },
                new Comuna { Id = 270, Nombre = "Río Verde", ProvinciaId = 45 },
                new Comuna { Id = 271, Nombre = "San Gregorio", ProvinciaId = 45 },
                new Comuna { Id = 272, Nombre = "Cabo de Hornos", ProvinciaId = 46 },
                new Comuna { Id = 273, Nombre = "Antártica", ProvinciaId = 46 },
                new Comuna { Id = 274, Nombre = "Porvenir", ProvinciaId = 47 },
                new Comuna { Id = 275, Nombre = "Primavera", ProvinciaId = 47 },
                new Comuna { Id = 276, Nombre = "Timaukel", ProvinciaId = 47 },
                new Comuna { Id = 277, Nombre = "Natales", ProvinciaId = 48 },
                new Comuna { Id = 278, Nombre = "Torres del Paine", ProvinciaId = 48 },
                new Comuna { Id = 279, Nombre = "Santiago", ProvinciaId = 49 },
                new Comuna { Id = 280, Nombre = "Cerrillos", ProvinciaId = 49 },
                new Comuna { Id = 281, Nombre = "Cerro Navia", ProvinciaId = 49 },
                new Comuna { Id = 282, Nombre = "Conchalí", ProvinciaId = 49 },
                new Comuna { Id = 283, Nombre = "El Bosque", ProvinciaId = 49 },
                new Comuna { Id = 284, Nombre = "Estación Central", ProvinciaId = 49 },
                new Comuna { Id = 285, Nombre = "Huechuraba", ProvinciaId = 49 },
                new Comuna { Id = 286, Nombre = "Independencia", ProvinciaId = 49 },
                new Comuna { Id = 287, Nombre = "La Cisterna", ProvinciaId = 49 },
                new Comuna { Id = 288, Nombre = "La Florida", ProvinciaId = 49 },
                new Comuna { Id = 289, Nombre = "La Granja", ProvinciaId = 49 },
                new Comuna { Id = 290, Nombre = "La Pintana", ProvinciaId = 49 },
                new Comuna { Id = 291, Nombre = "La Reina", ProvinciaId = 49 },
                new Comuna { Id = 292, Nombre = "Las Condes", ProvinciaId = 49 },
                new Comuna { Id = 293, Nombre = "Lo Barnechea", ProvinciaId = 49 },
                new Comuna { Id = 294, Nombre = "Lo Espejo", ProvinciaId = 49 },
                new Comuna { Id = 295, Nombre = "Lo Prado", ProvinciaId = 49 },
                new Comuna { Id = 296, Nombre = "Macul", ProvinciaId = 49 },
                new Comuna { Id = 297, Nombre = "Maipú", ProvinciaId = 49 },
                new Comuna { Id = 298, Nombre = "Ñuñoa", ProvinciaId = 49 },
                new Comuna { Id = 299, Nombre = "Pedro Aguirre Cerda", ProvinciaId = 49 },
                new Comuna { Id = 300, Nombre = "Peñalolén", ProvinciaId = 49 },
                new Comuna { Id = 301, Nombre = "Providencia", ProvinciaId = 49 },
                new Comuna { Id = 302, Nombre = "Pudahuel", ProvinciaId = 49 },
                new Comuna { Id = 303, Nombre = "Quilicura", ProvinciaId = 49 },
                new Comuna { Id = 304, Nombre = "Quinta Normal", ProvinciaId = 49 },
                new Comuna { Id = 305, Nombre = "Recoleta", ProvinciaId = 49 },
                new Comuna { Id = 306, Nombre = "Renca", ProvinciaId = 49 },
                new Comuna { Id = 307, Nombre = "San Joaquín", ProvinciaId = 49 },
                new Comuna { Id = 308, Nombre = "San Miguel", ProvinciaId = 49 },
                new Comuna { Id = 309, Nombre = "San Ramón", ProvinciaId = 49 },
                new Comuna { Id = 310, Nombre = "Vitacura", ProvinciaId = 49 },
                new Comuna { Id = 311, Nombre = "Puente Alto", ProvinciaId = 50 },
                new Comuna { Id = 312, Nombre = "Pirque", ProvinciaId = 50 },
                new Comuna { Id = 313, Nombre = "San José de Maipo", ProvinciaId = 50 },
                new Comuna { Id = 314, Nombre = "Colina", ProvinciaId = 51 },
                new Comuna { Id = 315, Nombre = "Lampa", ProvinciaId = 51 },
                new Comuna { Id = 316, Nombre = "Tiltil", ProvinciaId = 51 },
                new Comuna { Id = 317, Nombre = "San Bernardo", ProvinciaId = 52 },
                new Comuna { Id = 318, Nombre = "Buin", ProvinciaId = 52 },
                new Comuna { Id = 319, Nombre = "Calera de Tango", ProvinciaId = 52 },
                new Comuna { Id = 320, Nombre = "Paine", ProvinciaId = 52 },
                new Comuna { Id = 321, Nombre = "Melipilla", ProvinciaId = 53 },
                new Comuna { Id = 322, Nombre = "Alhué", ProvinciaId = 53 },
                new Comuna { Id = 323, Nombre = "Curacaví", ProvinciaId = 53 },
                new Comuna { Id = 324, Nombre = "María Pinto", ProvinciaId = 53 },
                new Comuna { Id = 325, Nombre = "San Pedro", ProvinciaId = 53 },
                new Comuna { Id = 326, Nombre = "Talagante", ProvinciaId = 54 },
                new Comuna { Id = 327, Nombre = "El Monte", ProvinciaId = 54 },
                new Comuna { Id = 328, Nombre = "Isla de Maipo", ProvinciaId = 54 },
                new Comuna { Id = 329, Nombre = "Padre Hurtado", ProvinciaId = 54 },
                new Comuna { Id = 330, Nombre = "Peñaflor", ProvinciaId = 54 },
                new Comuna { Id = 331, Nombre = "Valdivia", ProvinciaId = 35 },
                new Comuna { Id = 332, Nombre = "Corral", ProvinciaId = 35 },
                new Comuna { Id = 333, Nombre = "Lanco", ProvinciaId = 35 },
                new Comuna { Id = 334, Nombre = "Los Lagos", ProvinciaId = 35 },
                new Comuna { Id = 335, Nombre = "Máfil", ProvinciaId = 35 },
                new Comuna { Id = 336, Nombre = "Mariquina", ProvinciaId = 35 },
                new Comuna { Id = 337, Nombre = "Paillaco", ProvinciaId = 35 },
                new Comuna { Id = 338, Nombre = "Panguipulli", ProvinciaId = 35 },
                new Comuna { Id = 339, Nombre = "La Unión", ProvinciaId = 36 },
                new Comuna { Id = 340, Nombre = "Futrono", ProvinciaId = 36 },
                new Comuna { Id = 341, Nombre = "Lago Ranco", ProvinciaId = 36 },
                new Comuna { Id = 342, Nombre = "Río Bueno", ProvinciaId = 36 },
                new Comuna { Id = 343, Nombre = "Arica", ProvinciaId = 1 },
                new Comuna { Id = 344, Nombre = "Camarones", ProvinciaId = 1 },
                new Comuna { Id = 345, Nombre = "Putre", ProvinciaId = 2 },
                new Comuna { Id = 346, Nombre = "General Lagos", ProvinciaId = 2 }
                );
            context.Estados.AddOrUpdate(
                e => e.Id,
                new Estado { Id = 1, Nombre = "Sin Asignar"},
                new Estado { Id = 2, Nombre = "Asignados" },
                new Estado { Id = 3, Nombre = "En Curso" },
                new Estado { Id = 4, Nombre = "Concluidos" }
                );

            context.Deptos.AddOrUpdate(
              d => d.Id,
              new Depto { Id = 1, Nombre = "Despacho", SucursalId = 1 }
              );

            context.Especialidades.AddOrUpdate(
              es => es.Id,
              new Especialidad { Id = 1, Nombre = "Redes", Descripcion="encargado de la red" },
              new Especialidad { Id = 2, Nombre = "Soporte", Descripcion = "encargado de Soporte" },
              new Especialidad { Id = 3, Nombre = "Administrativo", Descripcion = "Trabajos Administrativos" },
              new Especialidad { Id = 4, Nombre = "Servicios", Descripcion = "Encargado servidores" }
              );
            context.Perfiles.AddOrUpdate(
              pe => pe.Id,
              new Perfil { Id = 1, Nombre = "Carlos", Apellido = "Godoy", Correo = "cg@sti.cl", CargoId = 1 },
              new Perfil { Id = 2, Nombre = "Marcelo", Apellido = "Zapata", Correo = "mz@sti.cl", CargoId = 2 },
              new Perfil { Id = 3, Nombre = "Juan", Apellido = "Fernandez", Correo = "jf@sti.cl", CargoId = 3 }
              );
            context.Sucursales.AddOrUpdate(
              su => su.Id,
              new Sucursal { Id = 1, Nombre = "Casa Matriz", Direccion = "Tucapel # 2827", ComunaId = 142},
              new Sucursal { Id = 2, Nombre = "Lota", Direccion = "Calle 1", ComunaId = 147 }
              );

            context.Logins.AddOrUpdate(
              lo => lo.Id,
              new Login { Id = 1, Nombre = "Carlos", Clave = "123" },
              new Login { Id = 2, Nombre = "Marcelo", Clave = "123" },
              new Login { Id = 3, Nombre = "Juan", Clave = "123" }
              );
            context.Cargos.AddOrUpdate(
              ca => ca.Id,
              new Cargo { Id = 1, Nombre = "Administrador" },
              new Cargo { Id = 2, Nombre = "Colaborador" },
              new Cargo { Id = 3, Nombre = "Usuario" }

              );

        }
    }
}